from enum import Enum, auto

class EntityType(Enum):
    """Type of code entity."""
    MODULE = auto()
    PACKAGE = auto()
    CLASS = auto()
    FUNCTION = auto()
    METHOD = auto()
    VARIABLE = auto()
    CONSTANT = auto()
    INTERFACE = auto()
    ENUM = auto()
    DECORATOR = auto()
    TYPE_ALIAS = auto()
    FILE = auto()
    NAMESPACE = auto()
    CONFIGURATION_FILE = auto()
    DEPLOYMENT = auto()
    CONTAINER = auto()
    SERVICE_DEFINITION = auto()
    API_CONTRACT = auto()
    MESSAGE_CONTRACT = auto()
    DATABASE_SCHEMA = auto()
    MIGRATION = auto()
    EXTERNAL_PACKAGE = auto()
    EXTERNAL_FRAMEWORK = auto()
    EXTERNAL_SERVICE = auto()
    EXTERNAL_API = auto()
    EXTERNAL_MODEL = auto()
    EXTERNAL_TOOL = auto()
    ORGANIZATION_NODE = auto()
    REPOSITORY_NODE = auto()
