"""Temporal diff engine for comparing graph states between commits."""

from dataclasses import dataclass, field
import datetime
import uuid
from typing import List, Dict, Set, Tuple

from src.domain.entities.code_entity import CodeEntity
from src.domain.entities.relationship import Relationship
from src.domain.entities.entity_version import EntityVersion
from src.domain.entities.relationship_version import RelationshipVersion
from src.domain.entities.change_event import ChangeEvent
from src.domain.enums.mutation_type import MutationType
from src.domain.value_objects.entity_id import SEID
from src.domain.value_objects.repository_id import RepositoryId
from src.infrastructure.git.commit_walker import GitFileChange
from src.infrastructure.git.rename_detection import RenameDetector
from src.infrastructure.git.move_detection import MoveDetector

@dataclass
class DiffResult:
    """Contains all the updates, versions, and events generated by the diff engine."""
    entities_to_save: List[CodeEntity] = field(default_factory=list)
    versions_to_save: List[EntityVersion] = field(default_factory=list)
    relationships_to_save: List[Relationship] = field(default_factory=list)
    relationship_versions_to_save: List[RelationshipVersion] = field(default_factory=list)
    change_events_to_save: List[ChangeEvent] = field(default_factory=list)

class TemporalDiffEngine:
    """Compares graph state at C_{n-1} with C_n and computes mutations."""

    def __init__(
        self,
        rename_detector: RenameDetector,
        move_detector: MoveDetector
    ) -> None:
        self.rename_detector = rename_detector
        self.move_detector = move_detector

    def compute_diff(
        self,
        repository_id: RepositoryId,
        commit_hash: str,
        previous_entities: List[CodeEntity],
        previous_relationships: List[Relationship],
        current_entities: List[CodeEntity],
        current_relationships: List[Relationship],
        file_changes: List[GitFileChange]
    ) -> DiffResult:
        """Compares previous graph state with current extracted graph state.
        
        Modifies SEIDs in current_entities and current_relationships in-place 
        to match resolved identities, then returns the DiffResult.
        """
        diff_result = DiffResult()

        # 1. Separate previous active entities
        prev_active_entities = [e for e in previous_entities if not e.metadata.get("is_deleted", False)]
        prev_active_map = {e.seid: e for e in prev_active_entities}

        # 2. Build file move map
        file_move_map = self.move_detector.build_file_move_map(file_changes)

        # 3. Step 1: Detect moved entities (due to file/folder renames)
        # We need to map deleted entities to created entities
        # Note: at this stage, current_entities all have temporary random SEIDs.
        # We will match them and update their SEIDs to match their previous identities.
        
        # Candidate deleted: active previously but not matching current by exact path/name
        # Let's define exact match criteria first to filter down candidate lists.
        current_exact_matches: Dict[Tuple[str, str, str], CodeEntity] = {}
        for c in current_entities:
            key = (c.location.file_path, c.name, c.entity_type.value)
            current_exact_matches[key] = c

        prev_exact_matches: Dict[Tuple[str, str, str], CodeEntity] = {}
        for p in prev_active_entities:
            key = (p.location.file_path, p.name, p.entity_type.value)
            prev_exact_matches[key] = p

        # Candidates for move/rename detection:
        unmatched_prev = [p for p in prev_active_entities if (p.location.file_path, p.name, p.entity_type.value) not in current_exact_matches]
        unmatched_curr = [c for c in current_entities if (c.location.file_path, c.name, c.entity_type.value) not in prev_exact_matches]

        # Process moves
        moved_associations = self.move_detector.associate_moved_entities(
            unmatched_prev, unmatched_curr, file_move_map
        )
        
        resolved_seids: Dict[SEID, SEID] = {}  # temporary_seid -> old_resolved_seid
        for prev_e, curr_e in moved_associations:
            curr_e.seid = prev_e.seid
            resolved_seids[curr_e.seid] = prev_e.seid
            
            # Remove from unmatched lists
            unmatched_prev.remove(prev_e)
            unmatched_curr.remove(curr_e)

            # Generate Move ChangeEvent and Version
            prev_version_count = prev_e.metadata.get("version_count", 1)
            new_version_ordinal = prev_version_count + 1
            
            # Update current entity metadata
            curr_e.metadata["version_count"] = new_version_ordinal
            
            diff_result.entities_to_save.append(curr_e)
            
            diff_result.versions_to_save.append(
                EntityVersion(
                    id=uuid.uuid4(),
                    seid=prev_e.seid,
                    commit_hash=commit_hash,
                    version_ordinal=new_version_ordinal,
                    mutation_type=MutationType.MOVED,
                    canonical_name=curr_e.qualified_name,
                    file_path=curr_e.location.file_path,
                    start_line=curr_e.location.start_line,
                    end_line=curr_e.location.end_line,
                    content_hash=curr_e.content_hash or "",
                    structural_fingerprint=curr_e.structural_fingerprint.value if curr_e.structural_fingerprint else "",
                    source_text=curr_e.source_text,
                    metadata=curr_e.metadata
                )
            )
            diff_result.change_events_to_save.append(
                ChangeEvent(
                    id=uuid.uuid4(),
                    repository_id=repository_id,
                    commit_hash=commit_hash,
                    seid=prev_e.seid,
                    change_type=MutationType.MOVED,
                    metadata={"previous_path": prev_e.location.file_path, "current_path": curr_e.location.file_path}
                )
            )

        # 4. Step 2: Detect Renames
        renamed_associations = self.rename_detector.detect_renames(
            unmatched_prev, unmatched_curr
        )
        for prev_seid, curr_e, score in renamed_associations:
            prev_e = prev_active_map[prev_seid]
            
            # Bind old SEID to current entity
            curr_e.seid = prev_seid
            resolved_seids[curr_e.seid] = prev_seid
            
            # Remove from unmatched lists
            unmatched_prev.remove(prev_e)
            unmatched_curr.remove(curr_e)

            prev_version_count = prev_e.metadata.get("version_count", 1)
            new_version_ordinal = prev_version_count + 1
            
            curr_e.metadata["version_count"] = new_version_ordinal
            diff_result.entities_to_save.append(curr_e)

            diff_result.versions_to_save.append(
                EntityVersion(
                    id=uuid.uuid4(),
                    seid=prev_seid,
                    commit_hash=commit_hash,
                    version_ordinal=new_version_ordinal,
                    mutation_type=MutationType.RENAMED,
                    canonical_name=curr_e.qualified_name,
                    file_path=curr_e.location.file_path,
                    start_line=curr_e.location.start_line,
                    end_line=curr_e.location.end_line,
                    content_hash=curr_e.content_hash or "",
                    structural_fingerprint=curr_e.structural_fingerprint.value if curr_e.structural_fingerprint else "",
                    source_text=curr_e.source_text,
                    metadata=curr_e.metadata
                )
            )
            diff_result.change_events_to_save.append(
                ChangeEvent(
                    id=uuid.uuid4(),
                    repository_id=repository_id,
                    commit_hash=commit_hash,
                    seid=prev_seid,
                    change_type=MutationType.RENAMED,
                    metadata={"previous_name": prev_e.name, "current_name": curr_e.name, "similarity": score}
                )
            )

        # 5. Process Exact Matches (same path and name)
        for key, curr_e in current_exact_matches.items():
            if curr_e in unmatched_curr:
                # If it's already processed as move/rename, skip
                continue

            prev_e = prev_exact_matches.get(key)
            if prev_e:
                curr_e.seid = prev_e.seid
                prev_version_count = prev_e.metadata.get("version_count", 1)
                
                # Check if content has modified
                modified = (
                    curr_e.content_hash != prev_e.content_hash or
                    (curr_e.structural_fingerprint.value if curr_e.structural_fingerprint else None) !=
                    (prev_e.structural_fingerprint.value if prev_e.structural_fingerprint else None)
                )

                if modified:
                    new_version_ordinal = prev_version_count + 1
                    curr_e.metadata["version_count"] = new_version_ordinal
                    
                    diff_result.entities_to_save.append(curr_e)
                    diff_result.versions_to_save.append(
                        EntityVersion(
                            id=uuid.uuid4(),
                            seid=prev_e.seid,
                            commit_hash=commit_hash,
                            version_ordinal=new_version_ordinal,
                            mutation_type=MutationType.MODIFIED,
                            canonical_name=curr_e.qualified_name,
                            file_path=curr_e.location.file_path,
                            start_line=curr_e.location.start_line,
                            end_line=curr_e.location.end_line,
                            content_hash=curr_e.content_hash or "",
                            structural_fingerprint=curr_e.structural_fingerprint.value if curr_e.structural_fingerprint else "",
                            source_text=curr_e.source_text,
                            metadata=curr_e.metadata
                        )
                    )
                    diff_result.change_events_to_save.append(
                        ChangeEvent(
                            id=uuid.uuid4(),
                            repository_id=repository_id,
                            commit_hash=commit_hash,
                            seid=prev_e.seid,
                            change_type=MutationType.MODIFIED,
                            metadata={"lines_changed": curr_e.location.end_line - curr_e.location.start_line}
                        )
                    )
                else:
                    # Content is identical, just update metadata and last seen commit
                    curr_e.metadata["version_count"] = prev_version_count
                    diff_result.entities_to_save.append(curr_e)

        # 6. Process newly CREATED entities
        for curr_e in unmatched_curr:
            # Generate new SEID
            curr_e.seid = SEID.generate()
            curr_e.metadata["version_count"] = 1
            
            diff_result.entities_to_save.append(curr_e)
            diff_result.versions_to_save.append(
                EntityVersion(
                    id=uuid.uuid4(),
                    seid=curr_e.seid,
                    commit_hash=commit_hash,
                    version_ordinal=1,
                    mutation_type=MutationType.CREATED,
                    canonical_name=curr_e.qualified_name,
                    file_path=curr_e.location.file_path,
                    start_line=curr_e.location.start_line,
                    end_line=curr_e.location.end_line,
                    content_hash=curr_e.content_hash or "",
                    structural_fingerprint=curr_e.structural_fingerprint.value if curr_e.structural_fingerprint else "",
                    source_text=curr_e.source_text,
                    metadata=curr_e.metadata
                )
            )
            diff_result.change_events_to_save.append(
                ChangeEvent(
                    id=uuid.uuid4(),
                    repository_id=repository_id,
                    commit_hash=commit_hash,
                    seid=curr_e.seid,
                    change_type=MutationType.CREATED,
                    metadata={}
                )
            )

        # 7. Process DELETED entities
        for prev_e in unmatched_prev:
            prev_version_count = prev_e.metadata.get("version_count", 1)
            new_version_ordinal = prev_version_count + 1
            
            # Update deleted status
            prev_e.metadata["is_deleted"] = True
            prev_e.metadata["version_count"] = new_version_ordinal
            
            diff_result.entities_to_save.append(prev_e)
            diff_result.versions_to_save.append(
                EntityVersion(
                    id=uuid.uuid4(),
                    seid=prev_e.seid,
                    commit_hash=commit_hash,
                    version_ordinal=new_version_ordinal,
                    mutation_type=MutationType.DELETED,
                    canonical_name=prev_e.qualified_name,
                    file_path=prev_e.location.file_path,
                    start_line=prev_e.location.start_line,
                    end_line=prev_e.location.end_line,
                    content_hash=prev_e.content_hash or "",
                    structural_fingerprint=prev_e.structural_fingerprint.value if prev_e.structural_fingerprint else "",
                    source_text=prev_e.source_text,
                    metadata=prev_e.metadata
                )
            )
            diff_result.change_events_to_save.append(
                ChangeEvent(
                    id=uuid.uuid4(),
                    repository_id=repository_id,
                    commit_hash=commit_hash,
                    seid=prev_e.seid,
                    change_type=MutationType.DELETED,
                    metadata={}
                )
            )

        # 8. Diff Relationships
        # Build maps for current resolved relationships
        # Update relationship entity source/target SEIDs using the resolved entity SEIDs
        for rel in current_relationships:
            # Check if source or target SEID needs to be updated because of resolved renames/moves
            if rel.source_seid in resolved_seids:
                rel.source_seid = resolved_seids[rel.source_seid]
            if rel.target_seid in resolved_seids:
                rel.target_seid = resolved_seids[rel.target_seid]

        # Key for relationship identification: (source_seid, target_seid, relationship_type)
        curr_rel_map = {
            (r.source_seid.value, r.target_seid.value, r.relationship_type.value): r
            for r in current_relationships
        }
        
        prev_active_rels = [r for r in previous_relationships if not r.metadata.get("is_deleted", False)]
        prev_rel_map = {
            (r.source_seid.value, r.target_seid.value, r.relationship_type.value): r
            for r in prev_active_rels
        }

        # Newly created relationships
        for key, curr_r in curr_rel_map.items():
            prev_r = prev_rel_map.get(key)
            if not prev_r:
                # CREATED relationship
                curr_r.metadata["is_deleted"] = False
                curr_r.metadata["version_count"] = 1
                diff_result.relationships_to_save.append(curr_r)
                
                diff_result.relationship_versions_to_save.append(
                    RelationshipVersion(
                        id=uuid.uuid4(),
                        relationship_id=curr_r.id,
                        commit_hash=commit_hash,
                        mutation_type=MutationType.CREATED,
                        version_ordinal=1,
                        metadata=curr_r.metadata
                    )
                )
            else:
                # Keep active
                curr_r.id = prev_r.id
                curr_r.metadata["is_deleted"] = False
                curr_r.metadata["version_count"] = prev_r.metadata.get("version_count", 1)
                diff_result.relationships_to_save.append(curr_r)

        # Deleted relationships
        for key, prev_r in prev_rel_map.items():
            if key not in curr_rel_map:
                # DELETED relationship
                prev_version_count = prev_r.metadata.get("version_count", 1)
                new_version_ordinal = prev_version_count + 1
                
                prev_r.metadata["is_deleted"] = True
                prev_r.metadata["version_count"] = new_version_ordinal
                diff_result.relationships_to_save.append(prev_r)
                
                diff_result.relationship_versions_to_save.append(
                    RelationshipVersion(
                        id=uuid.uuid4(),
                        relationship_id=prev_r.id,
                        commit_hash=commit_hash,
                        mutation_type=MutationType.DELETED,
                        version_ordinal=new_version_ordinal,
                        metadata=prev_r.metadata
                    )
                )

        return diff_result
