from src.infrastructure.persistence.repositories.sa_repository_repo import SARepositoryRepository
from src.infrastructure.persistence.repositories.sa_source_file_repo import SASourceFileRepository
from src.infrastructure.persistence.repositories.sa_code_entity_repo import SACodeEntityRepository
from src.infrastructure.persistence.repositories.sa_relationship_repo import SARelationshipRepository
from src.infrastructure.persistence.repositories.sa_commit_repo import SACommitRepository
from src.infrastructure.persistence.repositories.sa_entity_version_repo import SAEntityVersionRepository
from src.infrastructure.persistence.repositories.sa_relationship_version_repo import SARelationshipVersionRepository
from src.infrastructure.persistence.repositories.sa_change_event_repo import SAChangeEventRepository
from src.infrastructure.persistence.repositories.sa_snapshot_repo import SARepositorySnapshotRepository
from src.infrastructure.persistence.repositories.sa_metrics_repo import SAMetricsRepository
from src.infrastructure.persistence.repositories.sa_integrity_repo import SAIntegrityRepository
from src.infrastructure.persistence.repositories.sa_logic_repositories import (
    SALogicSignatureRepository,
    SALogicVersionRepository,
    SALogicTransitionRepository,
    SALogicEvidenceRepository,
    SABehaviorExplanationRepository,
    SABehaviorDriftRepository,
    SABehaviorPatternRepository,
    SALogicClusterRepository,
    SAOntologyNodeRepository,
)
from src.infrastructure.persistence.repositories.sa_concept_repositories import (
    SAConceptNodeRepository,
    SAConceptVersionRepository,
    SAConceptEvidenceRepository,
    SAConceptRelationshipRepository,
    SAConceptClusterRepository,
    SAConceptExplanationRepository,
    SAConceptMetricsRepository,
    SAConceptEvolutionRepository,
    SAConceptDriftRepository,
)
from src.infrastructure.persistence.repositories.sa_meta_repositories import (
    SAMetaTypeRepository,
    SAMetaDefinitionRepository,
    SAEmbeddingModelRepository,
    SAEmbeddingVersionRepository,
)
from src.infrastructure.persistence.repositories.sa_resolution_repos import (
    SASymbolGraphRepository,
    SASymbolReferenceRepository,
    SAVariableFlowRepository,
    SACrossFileResolutionRepository,
    SAExternalDependencyRepository,
    SAAIEvidenceRepository,
    SARepositoryArchitectureGraphRepository,
    SAArchitectureRelationshipRepository,
    SARepositoryStructureGraphRepository,
    SACompilerOutputVersionRepository,
    SAReasoningArtifactRepository,
    SAKnowledgeDriftRepository,
    SAExternalKnowledgeReferenceRepository,
)
from src.infrastructure.persistence.repositories.sa_capability_repos import (
    SACapabilityRepository,
    SACapabilityCandidateRepository,
    SACapabilityRelationshipRepository,
    SACapabilityFingerprintRepository,
    SACapabilityEvolutionRepository,
    SACapabilityTimelineRepository,
    SACapabilityDependencyRepository,
    SACapabilityHealthRepository,
    SACapabilityBlastRadiusRepository,
    SACapabilityProvenanceRepository,
    SACapabilityConfidenceRepository,
    SACapabilityOverlapRepository,
    SACapabilityStabilityRepository,
    SACapabilitySnapshotRepository,
    SACapabilityBoundaryRepository,
    SACapabilityCohesionRepository,
    SACapabilityCouplingRepository,
    SACapabilityEmbeddingRepository,
    SACapabilityTaxonomyCandidateRepository,
)

__all__ = [
    "SARepositoryRepository",
    "SASourceFileRepository",
    "SACodeEntityRepository",
    "SARelationshipRepository",
    "SACommitRepository",
    "SAEntityVersionRepository",
    "SARelationshipVersionRepository",
    "SAChangeEventRepository",
    "SARepositorySnapshotRepository",
    "SAMetricsRepository",
    "SAIntegrityRepository",
    "SALogicSignatureRepository",
    "SALogicVersionRepository",
    "SALogicTransitionRepository",
    "SALogicEvidenceRepository",
    "SABehaviorExplanationRepository",
    "SABehaviorDriftRepository",
    "SABehaviorPatternRepository",
    "SALogicClusterRepository",
    "SAOntologyNodeRepository",
    "SAConceptNodeRepository",
    "SAConceptVersionRepository",
    "SAConceptEvidenceRepository",
    "SAConceptRelationshipRepository",
    "SAConceptClusterRepository",
    "SAConceptExplanationRepository",
    "SAConceptMetricsRepository",
    "SAConceptEvolutionRepository",
    "SAConceptDriftRepository",
    "SAMetaTypeRepository",
    "SAMetaDefinitionRepository",
    "SAEmbeddingModelRepository",
    "SAEmbeddingVersionRepository",
    "SASymbolGraphRepository",
    "SASymbolReferenceRepository",
    "SAVariableFlowRepository",
    "SACrossFileResolutionRepository",
    "SAExternalDependencyRepository",
    "SAAIEvidenceRepository",
    "SARepositoryArchitectureGraphRepository",
    "SAArchitectureRelationshipRepository",
    "SARepositoryStructureGraphRepository",
    "SACompilerOutputVersionRepository",
    "SAReasoningArtifactRepository",
    "SAKnowledgeDriftRepository",
    "SAExternalKnowledgeReferenceRepository",
    "SACapabilityRepository",
    "SACapabilityCandidateRepository",
    "SACapabilityRelationshipRepository",
    "SACapabilityFingerprintRepository",
    "SACapabilityEvolutionRepository",
    "SACapabilityTimelineRepository",
    "SACapabilityDependencyRepository",
    "SACapabilityHealthRepository",
    "SACapabilityBlastRadiusRepository",
    "SACapabilityProvenanceRepository",
    "SACapabilityConfidenceRepository",
    "SACapabilityOverlapRepository",
    "SACapabilityStabilityRepository",
    "SACapabilitySnapshotRepository",
    "SACapabilityBoundaryRepository",
    "SACapabilityCohesionRepository",
    "SACapabilityCouplingRepository",
    "SACapabilityEmbeddingRepository",
    "SACapabilityTaxonomyCandidateRepository",
]
