"""
Phase 7A — ReasoningHypothesis

A candidate explanation generated by the HypothesisGenerationEngine and
scored by the HypothesisScoringEngine.

Multiple competing hypotheses are retained in the ReasoningResult so that:
  * The highest-scoring one becomes ``selected_hypothesis``.
  * Lower-scoring ones become ``alternative_hypotheses`` and give the
    consumer visibility into competing explanations.
  * Phase 7B/7C can refine scoring without changing the output schema.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class ReasoningHypothesis:
    """One candidate explanation for a reasoning question.

    Attributes:
        hypothesis_id:    Unique identifier for this hypothesis within a run.
        statement:        Human-readable hypothesis statement.
        supporting_ids:   source_ids of evidence that support this hypothesis.
        contradicting_ids: source_ids of evidence that contradict this hypothesis.
        score:            Numeric score in [0.0, 1.0] assigned by the scoring engine.
        is_selected:      True if this hypothesis was chosen as the best explanation.
        rationale:        Why this score was assigned.
        metadata:         Arbitrary extra data for debugging.
    """

    hypothesis_id: str
    statement: str
    supporting_ids: list[str] = field(default_factory=list)
    contradicting_ids: list[str] = field(default_factory=list)
    score: float = 0.0
    is_selected: bool = False
    rationale: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def validate(self) -> None:
        """Raise ValueError if invariants are violated."""
        if not (0.0 <= self.score <= 1.0):
            raise ValueError(
                f"ReasoningHypothesis.score must be in [0.0, 1.0], got {self.score!r}"
            )

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serialisable representation."""
        return {
            "hypothesis_id": self.hypothesis_id,
            "statement": self.statement,
            "supporting_ids": self.supporting_ids,
            "contradicting_ids": self.contradicting_ids,
            "score": self.score,
            "is_selected": self.is_selected,
            "rationale": self.rationale,
        }
