"""phase5_6_knowledge_fidelity

Revision ID: 094fdf1f7b48
Revises: 6077147c1fc3
Create Date: 2026-06-13 11:46:39.089498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094fdf1f7b48'
down_revision: Union[str, None] = '6077147c1fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('ontology_parent_candidate', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('valid_from_commit', sa.String(length=40), nullable=False),
    sa.Column('valid_to_commit', sa.String(length=40), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('artifact_version', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_artifacts_commit_range', 'knowledge_artifacts', ['repository_id', 'valid_from_commit', 'valid_to_commit'], unique=False)
    op.create_index('ix_knowledge_artifacts_repo', 'knowledge_artifacts', ['repository_id'], unique=False)
    op.create_index('ix_knowledge_artifacts_type', 'knowledge_artifacts', ['artifact_type'], unique=False)
    op.create_table('compiler_outputs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('generated_entities', sa.JSON(), nullable=False),
    sa.Column('generated_relationships', sa.JSON(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('frameworks_detected', sa.JSON(), nullable=False),
    sa.Column('semantic_hints', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compiler_outputs_file', 'compiler_outputs', ['file_id'], unique=False)
    op.create_index('ix_compiler_outputs_repo_commit', 'compiler_outputs', ['repository_id', 'commit_hash'], unique=False)
    op.create_table('seee_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('symbol_graph', sa.JSON(), nullable=False),
    sa.Column('type_evidence', sa.JSON(), nullable=False),
    sa.Column('call_sites', sa.JSON(), nullable=False),
    sa.Column('dependency_graph', sa.JSON(), nullable=False),
    sa.Column('api_evidence', sa.JSON(), nullable=False),
    sa.Column('database_evidence', sa.JSON(), nullable=False),
    sa.Column('event_evidence', sa.JSON(), nullable=False),
    sa.Column('ai_evidence', sa.JSON(), nullable=False),
    sa.Column('flow_signatures', sa.JSON(), nullable=False),
    sa.Column('structure_signatures', sa.JSON(), nullable=False),
    sa.Column('raw_signals', sa.JSON(), nullable=False),
    sa.Column('diagnostics', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seee_evidence_file', 'seee_evidence', ['file_id'], unique=False)
    op.create_index('ix_seee_evidence_repo_commit', 'seee_evidence', ['repository_id', 'commit_hash'], unique=False)
    op.add_column('code_entities', sa.Column('layer', sa.String(length=30), server_default='STRUCTURAL', nullable=False))
    op.add_column('relationships', sa.Column('layer', sa.String(length=30), server_default='STRUCTURAL', nullable=False))
    op.add_column('repositories', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.add_column('repository_snapshots', sa.Column('entity_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('repository_snapshots', sa.Column('relationship_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('repository_snapshots', sa.Column('behavior_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('repository_snapshots', sa.Column('concept_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('repository_snapshots', sa.Column('capability_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('repository_snapshots', sa.Column('dependency_graph_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_snapshots', 'dependency_graph_hash')
    op.drop_column('repository_snapshots', 'capability_count')
    op.drop_column('repository_snapshots', 'concept_count')
    op.drop_column('repository_snapshots', 'behavior_count')
    op.drop_column('repository_snapshots', 'relationship_count')
    op.drop_column('repository_snapshots', 'entity_count')
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_column('repositories', 'organization_id')
    op.drop_column('relationships', 'layer')
    op.drop_column('code_entities', 'layer')
    op.drop_index('ix_seee_evidence_repo_commit', table_name='seee_evidence')
    op.drop_index('ix_seee_evidence_file', table_name='seee_evidence')
    op.drop_table('seee_evidence')
    op.drop_index('ix_compiler_outputs_repo_commit', table_name='compiler_outputs')
    op.drop_index('ix_compiler_outputs_file', table_name='compiler_outputs')
    op.drop_table('compiler_outputs')
    op.drop_index('ix_knowledge_artifacts_type', table_name='knowledge_artifacts')
    op.drop_index('ix_knowledge_artifacts_repo', table_name='knowledge_artifacts')
    op.drop_index('ix_knowledge_artifacts_commit_range', table_name='knowledge_artifacts')
    op.drop_table('knowledge_artifacts')
    op.drop_table('organizations')
    op.drop_table('concept_candidates')
    op.drop_table('capability_candidates')
    # ### end Alembic commands ###
