"""phase5a_meta_ontology

Revision ID: 6077147c1fc3
Revises: b69e8eb01c06
Create Date: 2026-06-08 22:26:26.810465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6077147c1fc3'
down_revision: Union[str, None] = 'b69e8eb01c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_models',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('distance_metric', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_types',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embedding_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('version_string', sa.String(length=64), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['embedding_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_embedding_version_model', 'embedding_versions', ['model_id', 'version_string'], unique=True)
    op.create_table('meta_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type_id', sa.String(length=128), nullable=False),
    sa.Column('major_version', sa.Integer(), nullable=False),
    sa.Column('minor_version', sa.Integer(), nullable=False),
    sa.Column('patch_version', sa.Integer(), nullable=False),
    sa.Column('schema_definition', sa.JSON(), nullable=False),
    sa.Column('semantic_signature', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['meta_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meta_defs_type', 'meta_definitions', ['type_id'], unique=False)
    op.create_index('uq_meta_defs_version', 'meta_definitions', ['type_id', 'major_version', 'minor_version', 'patch_version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_meta_defs_version', table_name='meta_definitions')
    op.drop_index('ix_meta_defs_type', table_name='meta_definitions')
    op.drop_table('meta_definitions')
    op.drop_index('uq_embedding_version_model', table_name='embedding_versions')
    op.drop_table('embedding_versions')
    op.drop_table('meta_types')
    op.drop_table('embedding_models')
    # ### end Alembic commands ###
