"""temporal_hardening

Revision ID: b357ef00886f
Revises: 0001
Create Date: 2026-06-03 00:00:45.019107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b357ef00886f'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporal_accuracy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('rename_precision', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('rename_recall', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('move_precision', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('move_recall', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('event_accuracy', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('reconstruction_accuracy', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temporal_accuracy_repo', 'temporal_accuracy', ['repository_id'], unique=False)
    op.create_table('temporal_benchmarks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('scan_duration_ms', sa.Integer(), nullable=False),
    sa.Column('diff_throughput_nodes_sec', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reconstruction_latency_ms', sa.Integer(), nullable=False),
    sa.Column('db_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('memory_rss_bytes', sa.BigInteger(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temporal_benchmarks_commit', 'temporal_benchmarks', ['commit_hash'], unique=False)
    op.create_index('ix_temporal_benchmarks_repo', 'temporal_benchmarks', ['repository_id'], unique=False)
    op.create_table('temporal_integrity_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('target_seid', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommended_repair', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temporal_integrity_issues_repo', 'temporal_integrity_issues', ['repository_id'], unique=False)
    op.create_index('ix_temporal_integrity_issues_type', 'temporal_integrity_issues', ['violation_type'], unique=False)
    op.create_table('temporal_repair_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('issue_ids', sa.JSON(), nullable=False),
    sa.Column('repair_actions', sa.JSON(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temporal_repair_audits_repo', 'temporal_repair_audits', ['repository_id'], unique=False)
    op.add_column('change_events', sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False))
    
    with op.batch_alter_table('change_events') as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('repository_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('seid',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
               
    with op.batch_alter_table('code_entities') as batch_op:
        batch_op.alter_column('seid',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('file_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('repository_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('parent_seid',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
               
    with op.batch_alter_table('commits') as batch_op:
        batch_op.alter_column('repository_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
               
    op.add_column('entity_versions', sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False))
    
    with op.batch_alter_table('entity_versions') as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('seid',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.drop_constraint('ux_entity_versions_seid_commit', type_='unique')
               
    op.create_index('ux_entity_versions_seid_commit', 'entity_versions', ['seid', 'commit_hash'], unique=True)
    
    op.add_column('relationship_versions', sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False))
    
    with op.batch_alter_table('relationship_versions') as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('relationship_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
               
    with op.batch_alter_table('relationships') as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('repository_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('source_seid',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('target_seid',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
               
    with op.batch_alter_table('repositories') as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
               
    with op.batch_alter_table('repository_snapshots') as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('repository_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.drop_constraint('ux_snapshots_repo_commit', type_='unique')
               
    op.create_index('ux_snapshots_repo_commit', 'repository_snapshots', ['repository_id', 'commit_hash'], unique=True)
    
    with op.batch_alter_table('source_files') as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('repository_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('content_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('line_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('size_bytes',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
               
    op.drop_index('ix_source_files_repo_path', table_name='source_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_source_files_repo_path', 'source_files', ['repository_id', 'file_path'], unique=False)
    
    with op.batch_alter_table('source_files') as batch_op:
        batch_op.alter_column('size_bytes',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('line_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('content_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('repository_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
               
    op.drop_index('ux_snapshots_repo_commit', table_name='repository_snapshots')
    
    with op.batch_alter_table('repository_snapshots') as batch_op:
        batch_op.create_unique_constraint('ux_snapshots_repo_commit', ['repository_id', 'commit_hash'])
        batch_op.alter_column('repository_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
               
    with op.batch_alter_table('repositories') as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
               
    with op.batch_alter_table('relationships') as batch_op:
        batch_op.alter_column('target_seid',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('source_seid',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('repository_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
               
    with op.batch_alter_table('relationship_versions') as batch_op:
        batch_op.alter_column('relationship_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
               
    op.drop_column('relationship_versions', 'confidence')
    op.drop_index('ux_entity_versions_seid_commit', table_name='entity_versions')
    
    with op.batch_alter_table('entity_versions') as batch_op:
        batch_op.create_unique_constraint('ux_entity_versions_seid_commit', ['seid', 'commit_hash'])
        batch_op.alter_column('seid',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
               
    op.drop_column('entity_versions', 'confidence')
    
    with op.batch_alter_table('commits') as batch_op:
        batch_op.alter_column('repository_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
               
    with op.batch_alter_table('code_entities') as batch_op:
        batch_op.alter_column('parent_seid',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('repository_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('file_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('seid',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
               
    with op.batch_alter_table('change_events') as batch_op:
        batch_op.alter_column('seid',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('repository_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
               
    op.drop_column('change_events', 'confidence')
    op.drop_index('ix_temporal_repair_audits_repo', table_name='temporal_repair_audits')
    op.drop_table('temporal_repair_audits')
    op.drop_index('ix_temporal_integrity_issues_type', table_name='temporal_integrity_issues')
    op.drop_index('ix_temporal_integrity_issues_repo', table_name='temporal_integrity_issues')
    op.drop_table('temporal_integrity_issues')
    op.drop_index('ix_temporal_benchmarks_repo', table_name='temporal_benchmarks')
    op.drop_index('ix_temporal_benchmarks_commit', table_name='temporal_benchmarks')
    op.drop_table('temporal_benchmarks')
    op.drop_index('ix_temporal_accuracy_repo', table_name='temporal_accuracy')
    op.drop_table('temporal_accuracy')
    # ### end Alembic commands ###
