"""phase4_5_semantic_expansion

Revision ID: b69e8eb01c06
Revises: 0003_phase3
Create Date: 2026-06-08 17:30:16.089145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69e8eb01c06'
down_revision: Union[str, None] = '0003_phase3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_families',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('parent_concept_id', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canonical_flows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flow_type', sa.String(length=64), nullable=False),
    sa.Column('source_entity_id', sa.Uuid(), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=False),
    sa.Column('intermediate_entities', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cluster_key', sa.String(length=128), nullable=False),
    sa.Column('cluster_label', sa.String(length=256), nullable=False),
    sa.Column('cohesion_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_key')
    )
    op.create_table('framework_definitions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('framework_name', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canonical_behaviors',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('family_id', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['behavior_families.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('ontology_node_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_defined', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_concept_nodes_ontology_node', 'concept_nodes', ['ontology_node_id'], unique=False)
    op.create_index('ix_concept_nodes_repository', 'concept_nodes', ['repository_id'], unique=False)
    op.create_index('uq_repo_ontology_node', 'concept_nodes', ['repository_id', 'ontology_node_id'], unique=True)
    op.create_table('framework_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('framework_id', sa.String(length=128), nullable=False),
    sa.Column('annotation_identifier', sa.String(length=256), nullable=False),
    sa.Column('map_to_entity_role', sa.String(length=64), nullable=False),
    sa.Column('map_to_relationship', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['framework_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('framework_version_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('framework_id', sa.String(length=128), nullable=False),
    sa.Column('version_string', sa.String(length=64), nullable=False),
    sa.Column('supported_syntax_rules', sa.JSON(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['framework_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behavior_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_behavior_id', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=64), nullable=False),
    sa.Column('imports', sa.JSON(), nullable=False),
    sa.Column('calls', sa.JSON(), nullable=False),
    sa.Column('heuristics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_behavior_id'], ['canonical_behaviors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_behavior_lang_idx', 'behavior_aliases', ['canonical_behavior_id', 'language'], unique=True)
    op.create_table('concept_cluster_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['concept_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['concept_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_concept_cluster_members_cluster', 'concept_cluster_members', ['cluster_id'], unique=False)
    op.create_index('ix_concept_cluster_members_concept', 'concept_cluster_members', ['concept_id'], unique=False)
    op.create_index('uq_cluster_concept', 'concept_cluster_members', ['cluster_id', 'concept_id'], unique=True)
    op.create_table('concept_drift',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('baseline_commit', sa.String(length=40), nullable=False),
    sa.Column('current_commit', sa.String(length=40), nullable=False),
    sa.Column('drift_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('drift_category', sa.String(length=64), nullable=False),
    sa.Column('dimension_scores', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_concept_drift_concept', 'concept_drift', ['concept_id'], unique=False)
    op.create_table('concept_relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('from_concept_id', sa.Uuid(), nullable=False),
    sa.Column('to_concept_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.Enum('DEPENDS_ON', 'IMPLEMENTS', 'SUPPORTS', 'USES', 'REQUIRES', 'ENHANCES', 'REPLACES', name='conceptrelationshiptype'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_concept_id'], ['concept_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_concept_id'], ['concept_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_concept_relationships_from', 'concept_relationships', ['from_concept_id'], unique=False)
    op.create_index('ix_concept_relationships_repository_commit', 'concept_relationships', ['repository_id', 'commit_hash'], unique=False)
    op.create_index('ix_concept_relationships_to', 'concept_relationships', ['to_concept_id'], unique=False)
    op.create_table('concept_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_concept_versions_commit', 'concept_versions', ['commit_hash'], unique=False)
    op.create_index('ix_concept_versions_concept', 'concept_versions', ['concept_id'], unique=False)
    op.create_index('ix_concept_versions_concept_commit', 'concept_versions', ['concept_id', 'commit_hash'], unique=True)
    op.create_table('concept_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('concept_version_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('confidence_contribution', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_version_id'], ['concept_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_concept_evidence_target', 'concept_evidence', ['target_id'], unique=False)
    op.create_index('ix_concept_evidence_version', 'concept_evidence', ['concept_version_id'], unique=False)
    op.create_table('concept_evolution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_concept_version_id', sa.Uuid(), nullable=True),
    sa.Column('to_concept_version_id', sa.Uuid(), nullable=False),
    sa.Column('transition_type', sa.Enum('CONCEPT_CREATION', 'CONCEPT_MODIFICATION', 'CONCEPT_SPLIT', 'CONCEPT_MERGE', 'CONCEPT_REMOVAL', name='concepttransitiontype'), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_concept_version_id'], ['concept_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_concept_version_id'], ['concept_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_concept_evolution_to', 'concept_evolution', ['to_concept_version_id'], unique=False)
    op.create_table('concept_explanations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('concept_version_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_version_id'], ['concept_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_version_id')
    )
    op.create_table('concept_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('concept_version_id', sa.Uuid(), nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('in_degree', sa.Integer(), nullable=False),
    sa.Column('out_degree', sa.Integer(), nullable=False),
    sa.Column('degree_centrality', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('betweenness_centrality', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('pagerank_score', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('impact_score', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_version_id'], ['concept_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_version_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concept_metrics')
    op.drop_table('concept_explanations')
    op.drop_index('ix_concept_evolution_to', table_name='concept_evolution')
    op.drop_table('concept_evolution')
    op.drop_index('ix_concept_evidence_version', table_name='concept_evidence')
    op.drop_index('ix_concept_evidence_target', table_name='concept_evidence')
    op.drop_table('concept_evidence')
    op.drop_index('ix_concept_versions_concept_commit', table_name='concept_versions')
    op.drop_index('ix_concept_versions_concept', table_name='concept_versions')
    op.drop_index('ix_concept_versions_commit', table_name='concept_versions')
    op.drop_table('concept_versions')
    op.drop_index('ix_concept_relationships_to', table_name='concept_relationships')
    op.drop_index('ix_concept_relationships_repository_commit', table_name='concept_relationships')
    op.drop_index('ix_concept_relationships_from', table_name='concept_relationships')
    op.drop_table('concept_relationships')
    op.drop_index('ix_concept_drift_concept', table_name='concept_drift')
    op.drop_table('concept_drift')
    op.drop_index('uq_cluster_concept', table_name='concept_cluster_members')
    op.drop_index('ix_concept_cluster_members_concept', table_name='concept_cluster_members')
    op.drop_index('ix_concept_cluster_members_cluster', table_name='concept_cluster_members')
    op.drop_table('concept_cluster_members')
    op.drop_index('uq_behavior_lang_idx', table_name='behavior_aliases')
    op.drop_table('behavior_aliases')
    op.drop_table('framework_version_registry')
    op.drop_table('framework_mappings')
    op.drop_index('uq_repo_ontology_node', table_name='concept_nodes')
    op.drop_index('ix_concept_nodes_repository', table_name='concept_nodes')
    op.drop_index('ix_concept_nodes_ontology_node', table_name='concept_nodes')
    op.drop_table('concept_nodes')
    op.drop_table('canonical_behaviors')
    op.drop_table('framework_definitions')
    op.drop_table('concept_clusters')
    op.drop_table('canonical_flows')
    op.drop_table('behavior_families')
    # ### end Alembic commands ###
