"""phase6_capability_intelligence

Revision ID: e2088bcbd852
Revises: a8b9c10d2e3f
Create Date: 2026-06-15 16:20:35.515049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2088bcbd852'
down_revision: Union[str, None] = 'a8b9c10d2e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('capability_type', sa.String(length=64), nullable=False),
    sa.Column('maturity_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('coverage_score', sa.Float(), nullable=False),
    sa.Column('concepts', sa.JSON(), nullable=False),
    sa.Column('behaviors', sa.JSON(), nullable=False),
    sa.Column('flows', sa.JSON(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('relationships', sa.JSON(), nullable=False),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capabilities_repository', 'capabilities', ['repository_id'], unique=False)
    op.create_table('capability_dependencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('source_capability_id', sa.Uuid(), nullable=False),
    sa.Column('target_capability_id', sa.Uuid(), nullable=False),
    sa.Column('dependency_type', sa.String(length=64), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_dependencies_repository', 'capability_dependencies', ['repository_id'], unique=False)
    op.create_table('capability_evolution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_evolution_repository', 'capability_evolution', ['repository_id'], unique=False)
    op.create_table('capability_overlap',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('capability_a_id', sa.Uuid(), nullable=False),
    sa.Column('capability_b_id', sa.Uuid(), nullable=False),
    sa.Column('overlap_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_overlap_repository', 'capability_overlap', ['repository_id'], unique=False)
    op.create_table('capability_relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('source_capability_id', sa.Uuid(), nullable=False),
    sa.Column('target_capability_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('dependency_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_relationships_repository', 'capability_relationships', ['repository_id'], unique=False)
    op.create_table('capability_taxonomy_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('suggested_category', sa.String(length=256), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_taxonomy_candidates_repository', 'capability_taxonomy_candidates', ['repository_id'], unique=False)
    op.create_table('capability_blast_radius',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('blast_radius_score', sa.Float(), nullable=False),
    sa.Column('impacted_capabilities', sa.JSON(), nullable=False),
    sa.Column('impacted_services', sa.JSON(), nullable=False),
    sa.Column('impacted_apis', sa.JSON(), nullable=False),
    sa.Column('impacted_agents', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_blast_radius_capability', 'capability_blast_radius', ['capability_id'], unique=False)
    op.create_table('capability_boundaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('internal_entities', sa.Integer(), nullable=False),
    sa.Column('external_dependencies', sa.Integer(), nullable=False),
    sa.Column('boundary_strength', sa.Float(), nullable=False),
    sa.Column('leakage_detected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_boundaries_capability', 'capability_boundaries', ['capability_id'], unique=False)
    op.create_table('capability_cohesion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('internal_flow_density', sa.Float(), nullable=False),
    sa.Column('internal_concept_similarity', sa.Float(), nullable=False),
    sa.Column('internal_behavior_similarity', sa.Float(), nullable=False),
    sa.Column('cohesion_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_cohesion_capability', 'capability_cohesion', ['capability_id'], unique=False)
    op.create_table('capability_confidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_strength', sa.Float(), nullable=False),
    sa.Column('flow_cohesion', sa.Float(), nullable=False),
    sa.Column('concept_agreement', sa.Float(), nullable=False),
    sa.Column('behavior_agreement', sa.Float(), nullable=False),
    sa.Column('relationship_density', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_confidence_capability', 'capability_confidence', ['capability_id'], unique=False)
    op.create_table('capability_coupling',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('api_coupling', sa.Float(), nullable=False),
    sa.Column('database_coupling', sa.Float(), nullable=False),
    sa.Column('event_coupling', sa.Float(), nullable=False),
    sa.Column('shared_service_coupling', sa.Float(), nullable=False),
    sa.Column('shared_entity_coupling', sa.Float(), nullable=False),
    sa.Column('coupling_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_coupling_capability', 'capability_coupling', ['capability_id'], unique=False)
    op.create_table('capability_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_embeddings_capability', 'capability_embeddings', ['capability_id'], unique=False)
    op.create_table('capability_fingerprints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('concept_signature', sa.String(length=64), nullable=False),
    sa.Column('behavior_signature', sa.String(length=64), nullable=False),
    sa.Column('flow_signature', sa.String(length=64), nullable=False),
    sa.Column('relationship_signature', sa.String(length=64), nullable=False),
    sa.Column('architecture_signature', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_fingerprints_capability', 'capability_fingerprints', ['capability_id'], unique=False)
    op.create_table('capability_health',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('coverage_score', sa.Float(), nullable=False),
    sa.Column('ownership_score', sa.Float(), nullable=False),
    sa.Column('dependency_score', sa.Float(), nullable=False),
    sa.Column('complexity_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_health_capability', 'capability_health', ['capability_id'], unique=False)
    op.create_table('capability_provenance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('source_concepts', sa.JSON(), nullable=False),
    sa.Column('source_behaviors', sa.JSON(), nullable=False),
    sa.Column('source_flows', sa.JSON(), nullable=False),
    sa.Column('source_entities', sa.JSON(), nullable=False),
    sa.Column('discovery_algorithm', sa.String(length=64), nullable=False),
    sa.Column('discovery_version', sa.String(length=32), nullable=False),
    sa.Column('placement_score', sa.Float(), nullable=False),
    sa.Column('creation_commit', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_provenance_capability', 'capability_provenance', ['capability_id'], unique=False)
    op.create_table('capability_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('risk', sa.String(length=64), nullable=False),
    sa.Column('health', sa.JSON(), nullable=False),
    sa.Column('owners', sa.JSON(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('flows', sa.JSON(), nullable=False),
    sa.Column('timeline', sa.JSON(), nullable=False),
    sa.Column('drift', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_snapshots_capability', 'capability_snapshots', ['capability_id'], unique=False)
    op.create_table('capability_stability',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('stability_score', sa.Float(), nullable=False),
    sa.Column('stability_status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_stability_capability', 'capability_stability', ['capability_id'], unique=False)
    op.create_table('capability_timelines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_timelines_capability', 'capability_timelines', ['capability_id'], unique=False)
    op.execute("DROP TABLE IF EXISTS capability_candidates")
    op.create_table('capability_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('capability_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capability_candidates_repository', 'capability_candidates', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_capability_candidates_repository', table_name='capability_candidates')
    op.drop_table('capability_candidates')
    op.create_table('capability_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_capability_timelines_capability', table_name='capability_timelines')
    op.drop_table('capability_timelines')
    op.drop_index('ix_capability_stability_capability', table_name='capability_stability')
    op.drop_table('capability_stability')
    op.drop_index('ix_capability_snapshots_capability', table_name='capability_snapshots')
    op.drop_table('capability_snapshots')
    op.drop_index('ix_capability_provenance_capability', table_name='capability_provenance')
    op.drop_table('capability_provenance')
    op.drop_index('ix_capability_health_capability', table_name='capability_health')
    op.drop_table('capability_health')
    op.drop_index('ix_capability_fingerprints_capability', table_name='capability_fingerprints')
    op.drop_table('capability_fingerprints')
    op.drop_index('ix_capability_embeddings_capability', table_name='capability_embeddings')
    op.drop_table('capability_embeddings')
    op.drop_index('ix_capability_coupling_capability', table_name='capability_coupling')
    op.drop_table('capability_coupling')
    op.drop_index('ix_capability_confidence_capability', table_name='capability_confidence')
    op.drop_table('capability_confidence')
    op.drop_index('ix_capability_cohesion_capability', table_name='capability_cohesion')
    op.drop_table('capability_cohesion')
    op.drop_index('ix_capability_boundaries_capability', table_name='capability_boundaries')
    op.drop_table('capability_boundaries')
    op.drop_index('ix_capability_blast_radius_capability', table_name='capability_blast_radius')
    op.drop_table('capability_blast_radius')
    op.drop_index('ix_capability_taxonomy_candidates_repository', table_name='capability_taxonomy_candidates')
    op.drop_table('capability_taxonomy_candidates')
    op.drop_index('ix_capability_relationships_repository', table_name='capability_relationships')
    op.drop_table('capability_relationships')
    op.drop_index('ix_capability_overlap_repository', table_name='capability_overlap')
    op.drop_table('capability_overlap')
    op.drop_index('ix_capability_evolution_repository', table_name='capability_evolution')
    op.drop_table('capability_evolution')
    op.drop_index('ix_capability_dependencies_repository', table_name='capability_dependencies')
    op.drop_table('capability_dependencies')
    op.drop_index('ix_capabilities_repository', table_name='capabilities')
    op.drop_table('capabilities')
    # ### end Alembic commands ###
