"""Domain entity representing a stable, named logic signature within a repository."""

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from src.domain.enums.language import SupportedLanguage
from src.domain.exceptions import InvalidEntityException
from src.domain.value_objects.repository_id import RepositoryId


@dataclass
class LogicSignature:
    """
    A LogicSignature represents a named, repository-scoped behavioral contract.

    It is the stable anchor point for tracking how a particular piece of logic
    (e.g., "bcrypt password verification") evolves across commits.  Multiple
    LogicVersion records may be attached to a single LogicSignature.
    """

    id: uuid.UUID
    """Deterministic UUID5 generated by LogicIdentityService."""

    repository_id: RepositoryId
    """The repository this logic signature belongs to."""

    canonical_name: str
    """Human-readable, repository-unique name (e.g., 'auth_bcrypt_verification')."""

    language: SupportedLanguage
    """Primary programming language of the detected implementation."""

    ontology_node_id: str | None
    """Dot-path reference into the ontology tree (e.g., 'security.authentication.hash_comparison').
    None if the signature has not yet been classified."""

    description: str
    """Free-text description of what this logic does."""

    created_at: datetime
    """UTC timestamp when this signature was first registered."""

    metadata: dict[str, Any] = field(default_factory=dict)
    """Arbitrary extensible metadata for tooling and reporting."""

    def validate(self) -> None:
        """
        Validate the invariants of this LogicSignature.

        Raises:
            InvalidEntityException: If canonical_name is empty.
        """
        if not self.canonical_name or not self.canonical_name.strip():
            raise InvalidEntityException(
                f"LogicSignature.canonical_name must not be empty (id={self.id})"
            )

    @property
    def file_path(self) -> str:
        return self.metadata.get("file_path", "unknown")

    @property
    def entity_seid(self) -> str:
        return self.metadata.get("entity_seid", "")

    @property
    def entity_name(self) -> str:
        return self.metadata.get("entity_name", self.canonical_name)

    @property
    def entity_type(self) -> str:
        return self.metadata.get("entity_type", "FUNCTION")
