from enum import Enum

class DecisionType(str, Enum):
    ARCHITECTURAL = "ARCHITECTURAL"
    TECHNOLOGY_ADOPTION = "TECHNOLOGY_ADOPTION"
    TECHNOLOGY_REMOVAL = "TECHNOLOGY_REMOVAL"
    CAPABILITY_CREATION = "CAPABILITY_CREATION"
    CAPABILITY_SPLIT = "CAPABILITY_SPLIT"
    CAPABILITY_MERGE = "CAPABILITY_MERGE"
    OWNERSHIP_CHANGE = "OWNERSHIP_CHANGE"
    SCALING = "SCALING"
    PERFORMANCE = "PERFORMANCE"
    SECURITY = "SECURITY"
    COMPLIANCE = "COMPLIANCE"
    AI_ADOPTION = "AI_ADOPTION"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    DATA_MODEL = "DATA_MODEL"
    REFACTORING = "REFACTORING"
    UNKNOWN = "UNKNOWN"
