from enum import Enum

class IntentType(str, Enum):
    SCALABILITY = "SCALABILITY"
    RELIABILITY = "RELIABILITY"
    SECURITY = "SECURITY"
    LATENCY = "LATENCY"
    COUPLING_REDUCTION = "COUPLING_REDUCTION"
    COST_REDUCTION = "COST_REDUCTION"
    AI_ENABLEMENT = "AI_ENABLEMENT"
    COMPLIANCE = "COMPLIANCE"
    OBSERVABILITY = "OBSERVABILITY"
    UNKNOWN = "UNKNOWN"
