"""Pydantic API schemas for Phase 7A Reasoning Intelligence Layer requests and responses."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


# ── Request schemas ────────────────────────────────────────────────────────────

class ReasoningQueryRequest(BaseModel):
    """API request to ask a reasoning question over the knowledge graph."""
    repository_id: str = Field(..., description="UUID of the target repository.")
    commit_hash: str = Field(..., description="Current HEAD commit hash of the repository.")
    query: str = Field(..., description="Natural-language question to reason about.")
    capability_version: str = Field("unknown", description="Version hash of the capability graph.")
    ontology_version: str = Field("unknown", description="Version hash of the concept/ontology graph.")
    compiler_version: str = Field("unknown", description="Semantic compiler version string.")
    use_cache: bool = Field(True, description="Whether to use cached results for repeated queries.")


class CacheInvalidationRequest(BaseModel):
    """Request to invalidate all cached reasoning results for a repository."""
    repository_id: str = Field(..., description="Repository UUID to invalidate cache for.")


# ── Nested response schemas ────────────────────────────────────────────────────

class ConfidenceSchema(BaseModel):
    """Confidence score and tier."""
    score: float
    level: str
    rationale: str


class LimitationSchema(BaseModel):
    """A known gap or limitation in the reasoning result."""
    reason: str
    affected_area: str
    impact: str


class HypothesisSchema(BaseModel):
    """A candidate explanation generated by the reasoning engine."""
    hypothesis_id: str
    statement: str
    supporting_ids: List[str] = Field(default_factory=list)
    contradicting_ids: List[str] = Field(default_factory=list)
    score: float
    is_selected: bool
    rationale: str = ""


class ReasoningStepSchema(BaseModel):
    """One step in the reasoning pipeline trace."""
    step_index: int
    step_type: str
    description: str
    inputs: List[str] = Field(default_factory=list)
    outputs: List[str] = Field(default_factory=list)
    executed_at: datetime
    duration_ms: Optional[float] = None


class ReasoningChainSchema(BaseModel):
    """Full step-by-step pipeline audit trail."""
    execution_id: str
    total_steps: int
    steps: List[ReasoningStepSchema] = Field(default_factory=list)


class ProvenanceNodeSchema(BaseModel):
    """A node in the evidence provenance DAG."""
    node_id: str
    node_type: str
    label: str
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ProvenanceEdgeSchema(BaseModel):
    """A directed edge in the evidence provenance DAG."""
    from_id: str = Field(alias="from")
    to_id: str = Field(alias="to")
    relationship: str

    class Config:
        populate_by_name = True


class ProvenanceGraphSchema(BaseModel):
    """Full evidence provenance DAG for one reasoning conclusion."""
    conclusion_id: str
    conclusion: str
    derived_from: List[str] = Field(default_factory=list)
    nodes: List[ProvenanceNodeSchema] = Field(default_factory=list)
    edges: List[ProvenanceEdgeSchema] = Field(default_factory=list)


class EvidenceSchema(BaseModel):
    """One validated evidence node."""
    source_id: str
    source_type: str
    description: str
    weight: float
    validated: bool
    metadata: Dict[str, Any] = Field(default_factory=dict)


class SnapshotSchema(BaseModel):
    """Graph-state snapshot at time of reasoning execution."""
    repository_id: str
    commit_hash: str
    capability_version: str
    ontology_version: str
    compiler_version: str
    reasoning_version: str
    snapshot_at: datetime


# ── Primary response schema ────────────────────────────────────────────────────

class ReasoningResultResponse(BaseModel):
    """Full auditable response from a Phase 7A reasoning query."""
    execution_id: str
    question: str
    answer: str
    confidence: ConfidenceSchema
    reasoning_chain: ReasoningChainSchema
    provenance_graph: ProvenanceGraphSchema
    evidence: List[EvidenceSchema] = Field(default_factory=list)
    selected_hypothesis: Optional[HypothesisSchema] = None
    alternative_hypotheses: List[HypothesisSchema] = Field(default_factory=list)
    limitations: List[LimitationSchema] = Field(default_factory=list)
    generated_at: datetime
    source_ids: List[str] = Field(default_factory=list)
    snapshot: Optional[SnapshotSchema] = None

    class Config:
        from_attributes = True


class CacheStatusResponse(BaseModel):
    """Cache status for the reasoning engine."""
    cache_size: int
    message: str


class CacheInvalidationResponse(BaseModel):
    """Response from a cache invalidation request."""
    repository_id: str
    entries_removed: int
    message: str


class ReasoningHealthResponse(BaseModel):
    """Health/status check for the reasoning API."""
    status: str
    reasoning_version: str
    cache_size: int
    registered_strategies: List[str]
